version: '3.7'

services:
  web:
    build: app
    container_name: wagtail-postgres-web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 80:8000
    env_file:
      - /var/.env
